/* =====================================================================
   COUCHE COMMUNE À TOUS LES EXPORTS EXCEL (toutes salles, toutes vues)
   · identité ECOBANK BLUE PREMIUM : remappage de la palette historique
   · couche TypeSafe + JEV : feuille « TypeSafe » ajoutée à chaque classeur
   ===================================================================== */
const PM_BLUE_MAP={'00415E':'001B4D','005C83':'003DA5','00344B':'001B4D','003B5C':'002B73','00506F':'002B73','0A6F95':'2563EB','0A7BA8':'2563EB','0A6F99':'2563EB','1A86B3':'2563EB','3F8FB5':'2563EB','2EA3D6':'06B6D4','19B5A5':'06B6D4','5FC4B8':'67E8F9',
  '8CC63F':'C8A951','A6D867':'E2CF8F','B5D98A':'E9DDB0','B8E07A':'E2CF8F','6BA23A':'16A34A','4E8A2E':'15803D','12333F':'0F172A','3E5C6B':'334155','274A57':'334155','5B7686':'64748B','EEF4F7':'F5F9FF','E9F1F6':'EAF2FF','EEF6FA':'F5F9FF','E7F0F4':'EAF2FF','F4F8FA':'F5F9FF','F6FAFC':'F5F9FF',
  'CFE0E7':'DBE6F7','E1EBF0':'E2E8F0','E3EDF2':'E2E8F0','C0392B':'DC2626','922B21':'991B1B','E0674F':'F97316','D96C2C':'F97316','B67D1C':'D97706','D4A13A':'F59E0B','D4912A':'F59E0B','F2B632':'F59E0B','C98A1E':'D97706'};
function pmBlueRemap(x){ return x.replace(/(rgb="(?:FF)?|srgbClr val="|fill="|color="|w:fill="|w:color="|w:val=")([0-9A-Fa-f]{6})"/g,(m,a,h)=>{ const n=PM_BLUE_MAP[h.toUpperCase()]; return n?a+n+'"':m; }); }
function pmTsRows(){ const rows=[], T=(typeof TSX!=='undefined'&&TSX.n)?Object.values(TSX.byRef):[], J=(typeof JEV!=='undefined'&&JEV.res)?JEV.res:null;
  rows.push({t:'title',v:['COUCHE TYPESAFE & JEV — JUGEMENTS, CONFIANCE ET PROBABILITÉS']});
  rows.push({t:'sub',v:['TypeSafe (jev-latest) ne produit aucun chiffre : motif, crédibilité, cohérence, urgence, orientation. Les montants, classes BCEAO / IFRS 9 / ACTE 7 restent calculés par APEX. Confiance faible → revue analyste.']});
  if(J){ const p=J.ptf.pd[12]; rows.push({t:'kpi',v:['JEV · PD 12M (sains)',(100*p.v).toFixed(1).replace('.',',')+' %',jevLbl(p.prov)]}); if(p.prov.avertissement) rows.push({t:'warn',v:['⚠ '+p.prov.avertissement]}); }
  else rows.push({t:'sub',v:['JEV : non calibré pour cet export (aucune archive d\'arrêtés).']});
  if(J&&J.adv){ const A=J.adv; rows.push({t:'kpi',v:['Analyses avancées · avant défaut (sain)',A.ttd?A.ttd[0].toFixed(0)+' mois':'—','MARKOV · matrice fondamentale']}); rows.push({t:'kpi',v:['Guérison 31-60 j · 61-90 j',(100*A.cure[0]).toFixed(1)+' % · '+(100*A.cure[1]).toFixed(1)+' %','MARKOV · absorption']});
    rows.push({t:'kpi',v:['PD 12M · IC 90 %',(100*A.boot.lo).toFixed(1)+' % – '+(100*A.boot.hi).toFixed(1)+' %','SIMULATED · bootstrap Dirichlet']}); if(A.back) rows.push({t:'kpi',v:['Backtest (dernier mois)',A.back.exp.toFixed(1)+' prévues · '+A.back.obs+' observées','EMPIRICAL · hors échantillon']}); rows.push({t:'kpi',v:['Stress inverse',(A.rev.factor).toFixed(2)+' × double la PD 12M','STRESS']}); }
  if(!T.length){ rows.push({t:'kpi',v:['TypeSafe','en attente d\'enrichissement','Exporter le lot (salle JEV → « ⇩ Lot TypeSafe »), l\'enrichir sur le poste connecté, puis recharger le classeur retourné.']}); return rows; }
  rows.push({t:'kpi',v:['TypeSafe · retours lus',String(T.length),(TSX.meta&&TSX.meta.modele||'jev-latest')+' · '+(TSX.src&&TSX.src.name||'')]});
  rows.push({t:'kpi',v:['Revue analyste',String(T.filter(t=>t.statut==='Revue analyste').length),'confiance faible, incohérence ou divergence d\'auto-cohérence']});
  { const SC={}; T.forEach(t=>Object.entries(t.scen||{}).forEach(([k,v])=>{ if(v>=0.6) SC[k]=(SC[k]||0)+1; })); const ks=Object.entries(SC).sort((a,b)=>b[1]-a[1]); if(ks.length) rows.push({t:'kpi',v:['Stress narratif · dossiers exposés',ks.map(([k,n])=>k.replace(/_/g,' ')+' : '+n).join(' · '),'exposition jugée par l\'analyse sémantique']}); }
  rows.push({t:'hdr',v:['Référence','Motif','Confiance','Crédibilité','Promesse vs bascule','Urgence','Orientation','Action recommandée','Statut retenu','JEV PD 12M','Revue / contrôles']});
  const cp=J?new Map(J.cps.map(c=>[String(c.ref).trim(),c])):new Map();
  T.forEach(t=>{ const c=cp.get(t.ref); rows.push({t:'row',v:[t.ref,(typeof TS_MOTIF!=='undefined'&&TS_MOTIF[t.motif])||t.motif||(t.commentaire?'en attente':'sans commentaire'),t.cMotif!=null?Math.round(100*t.cMotif)+' %':'',t.cred!=null?TS_CRED[t.cred]:'',t.position||'',t.urg!=null?t.urg+' / 4':'',t.routage||'',t.action||'',t.statut||'',c?(100*c.pd[12].v).toFixed(1).replace('.',',')+' % '+c.pd[12].prov.source:'',(t.revue||[]).concat(t.qc||[]).join(' · ')],rv:t.statut==='Revue analyste'}); });
  return rows; }
async function pmBlue(blob,name){ try{ const z=await JSZip.loadAsync(await blob.arrayBuffer(),{createFolders:false}); const core=z.file('docProps/core.xml'); if(core&&/APEX-RI/.test(await core.async('string'))) return null;
    for(const f of Object.keys(z.files)) if(/^xl\/(styles\.xml|worksheets\/[^/]+\.xml|charts\/[^/]+\.xml|drawings\/[^/]+\.xml|theme\/[^/]+\.xml)$/.test(f)) z.file(f,pmBlueRemap(await z.file(f).async('string')));
    let wb=await z.file('xl/workbook.xml').async('string');
    if(!/<sheet [^>]*name="(TypeSafe|_TYPESAFE)"/i.test(wb)){ // feuille TypeSafe & JEV
      let st=await z.file('xl/styles.xml').async('string'); const add=(tag,xml)=>{ const m=st.match(new RegExp('<'+tag+' count="(\\d+)"')); const n=m?+m[1]:0; st=st.replace(new RegExp('<'+tag+' count="\\d+"'),'<'+tag+' count="'+(n+xml.length)+'"').replace('</'+tag+'>',xml.join('')+'</'+tag+'>'); return n; };
      const f0=add('fonts',['<font><b/><sz val="16"/><color rgb="FF001B4D"/><name val="Segoe UI"/></font>','<font><sz val="9"/><color rgb="FF334155"/><name val="Segoe UI"/></font>','<font><b/><sz val="9"/><color rgb="FFFFFFFF"/><name val="Segoe UI"/></font>','<font><b/><sz val="10"/><color rgb="FF003DA5"/><name val="Segoe UI"/></font>','<font><b/><sz val="9"/><color rgb="FF92400E"/><name val="Segoe UI"/></font>','<font><b/><sz val="9"/><color rgb="FFDC2626"/><name val="Segoe UI"/></font>']);
      const fl0=add('fills',['<fill><patternFill patternType="solid"><fgColor rgb="FF001B4D"/><bgColor indexed="64"/></patternFill></fill>','<fill><patternFill patternType="solid"><fgColor rgb="FFEAF2FF"/><bgColor indexed="64"/></patternFill></fill>','<fill><patternFill patternType="solid"><fgColor rgb="FFFEF3C7"/><bgColor indexed="64"/></patternFill></fill>','<fill><patternFill patternType="solid"><fgColor rgb="FFFFF5F5"/><bgColor indexed="64"/></patternFill></fill>']);
      const b0=add('borders',['<border><left/><right/><top/><bottom style="medium"><color rgb="FFC8A951"/></bottom><diagonal/></border>','<border><left/><right/><top/><bottom style="thin"><color rgb="FFE2E8F0"/></bottom><diagonal/></border>']);
      const al='<alignment vertical="center" wrapText="1"/>', xf=(f,fl,b)=>`<xf numFmtId="0" fontId="${f}" fillId="${fl}" borderId="${b}" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1">${al}</xf>`;
      const x0=add('cellXfs',[xf(f0,0,0),xf(f0+1,0,0),xf(f0+2,fl0,b0),xf(f0+1,0,b0+1),xf(f0+3,fl0+1,b0+1),xf(f0+4,fl0+2,0),xf(f0+5,fl0+3,b0+1)]);
      z.file('xl/styles.xml',st);
      const S={title:x0,sub:x0+1,hdr:x0+2,row:x0+3,kpi:x0+4,warn:x0+5,rv:x0+6}, col=c=>String.fromCharCode(65+c), esc=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
      const rows=pmTsRows().map((o,i)=>{ const s=o.rv?S.rv:S[o.t]; return `<row r="${i+1}"${o.t==='title'?' ht="28" customHeight="1"':o.t==='sub'?' ht="30" customHeight="1"':''}>${o.v.map((v,j)=>`<c r="${col(j)}${i+1}" s="${s}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`).join('')}</row>`; });
      const merges=pmTsRows().map((o,i)=>o.t==='title'||o.t==='sub'||o.t==='warn'?`<mergeCell ref="A${i+1}:J${i+1}"/>`:o.t==='kpi'?`<mergeCell ref="C${i+1}:J${i+1}"/>`:'').filter(Boolean);
      const xml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><tabColor rgb="FF06B6D4"/></sheetPr><sheetViews><sheetView showGridLines="0" workbookViewId="0"/></sheetViews><cols><col min="1" max="1" width="24" customWidth="1"/><col min="2" max="2" width="22" customWidth="1"/><col min="3" max="9" width="14" customWidth="1"/><col min="10" max="10" width="60" customWidth="1"/></cols><sheetData>${rows.join('')}</sheetData>${merges.length?`<mergeCells count="${merges.length}">${merges.join('')}</mergeCells>`:''}<pageMargins left="0.3" right="0.3" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`;
      const p='xl/worksheets/sheetSemx.xml'; z.file(p,xml);
      let rel=await z.file('xl/_rels/workbook.xml.rels').async('string'); rel=rel.replace('</Relationships>','<Relationship Id="rIdSemx" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheetSemx.xml"/></Relationships>'); z.file('xl/_rels/workbook.xml.rels',rel);
      const ids=[...wb.matchAll(/sheetId="(\d+)"/g)].map(m=>+m[1]); wb=wb.replace('</sheets>',`<sheet name="TypeSafe" sheetId="${Math.max(0,...ids)+1}" r:id="rIdSemx"/></sheets>`); if(!/xmlns:r=/.test(wb.slice(0,600))) wb=wb.replace('<workbook ','<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '); z.file('xl/workbook.xml',wb);
      let ct=await z.file('[Content_Types].xml').async('string'); ct=ct.replace('</Types>','<Override PartName="/'+p+'" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'); z.file('[Content_Types].xml',ct);
      const app=z.file('docProps/app.xml'); if(app){ let a=await app.async('string'); a=a.replace(/<HeadingPairs>[\s\S]*?<\/HeadingPairs>/,'').replace(/<TitlesOfParts>[\s\S]*?<\/TitlesOfParts>/,''); z.file('docProps/app.xml',a); } }
    const out=await z.generateAsync({type:'blob',compression:'DEFLATE',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}); return out;
  }catch(e){ console.warn('Blue Premium / TypeSafe',e); return null; } }
