/* =====================================================================
   CREDIT RISK INTELLIGENCE — WORD, POWERPOINT, PDF (même source riModel)
   + AGENT EXPORT : orchestre, contrôle et journalise tous les exports
   ===================================================================== */
const RIX={eb:'003DA5',deep:'001B4D',corp:'002B73',bright:'2563EB',cyan:'06B6D4',gold:'C8A951',ok:'16A34A',warn:'F59E0B',alert:'F97316',crit:'DC2626',light:'EAF2FF',pale:'F5F9FF',ink:'0F172A',ink2:'334155',neu:'64748B',line:'DBE6F7'};
const riLong=d=>d.getDate()+' '+RI_MOIS[d.getMonth()]+' '+d.getFullYear();
function riCards(m){ const K=m.K, KP=m.KP, d=k=>KP&&KP[k]?(K[k]-KP[k])/Math.abs(KP[k]):null, crit=m.watch.filter(o=>o.lvl==='CRITICAL');
  return [['TOTAL EXPOSURE',riMd(K.enc),'XOF · '+fmtN(K.n)+' clients',d('enc'),0,RIX.eb],['TOTAL ARREARS',riMd(K.pdo),'XOF · '+fmtN(K.nArr)+' clients',d('pdo'),1,RIX.cyan],['31–60 DAYS',riMd(K.b2),fmtN(K.nb[2])+' clients',d('b2'),1,RIX.warn],['61–90 DAYS',riMd(K.b3),fmtN(K.nb[3])+' clients',d('b3'),1,RIX.alert],['> 90 DAYS / S3',riMd(K.b4),fmtN(K.nb[4])+' clients',d('b4'),1,RIX.crit],
    ['STAGE 2',riMd(K.s2),riPct(K.s2/(K.enc||1))+' de l\'encours',d('s2'),1,RIX.gold],['STAGE 3',riMd(K.s3),riPct(K.s3/(K.enc||1))+' de l\'encours',d('s3'),1,RIX.crit],['PROVISIONS (ECL)',riMd(K.ecl),'couverture '+riPct(K.ecl/(K.enc||1)),d('ecl'),1,RIX.cyan],['WATCHLIST',fmtN(m.watch.length),'dossiers · '+riMd(m.watch.reduce((s,o)=>s+o.enc,0)),null,1,RIX.warn],['CRITICAL',riMd(crit.reduce((s,o)=>s+o.enc,0)),fmtN(crit.length)+' dossiers critiques',null,1,RIX.crit]]; }
const riVar=(v,bad)=>v==null?'—':(v>0?'▲ ':v<0?'▼ ':'■ ')+riPct(v);
const riVarC=(v,bad)=>v==null||Math.abs(v)<1e-9?RIX.neu:((bad?v<=0:v>=0)?RIX.ok:RIX.crit);

/* ---------- visuels 3D (kit g3 en Blue Premium) partagés par Word, PDF et PowerPoint ---------- */
function riVisuals(m){ const V=[], P=['#003DA5','#C8A951','#DC2626'];
  try{ const labs=m.months.map(x=>x.label.slice(0,5));
    V.push(['Tendance des impayés, Stage 2 et Stage 3',g3Lines({title:'Portfolio trend',sub:'impayés · Stage 2 · Stage 3 (XOF)',labels:labs,series:[{name:'Impayés',values:m.months.map(x=>x.k.pdo),color:'#06B6D4'},{name:'Stage 2',values:m.months.map(x=>x.k.s2),color:'#C8A951'},{name:'Stage 3',values:m.months.map(x=>x.k.s3),color:'#DC2626'}],fmt:g3Md,w:900,h:380})]);
    V.push(['Répartition de l\'encours par stage IFRS 9',g3Donut({title:'Risk distribution',sub:'encours par stage',labels:['Stage 1','Stage 2','Stage 3'],values:[m.K.enc-m.K.s2-m.K.s3,m.K.s2,m.K.s3],colors:P,w:900,h:380})]);
    V.push(['Encours par tranche d\'impayé',g3Bars({title:'Exposure by arrears bucket',sub:'XOF',labels:RI_BK,values:m.K.eb,colors:['#16A34A','#06B6D4','#F59E0B','#F97316','#DC2626'],w:900,h:380})]);
    if(m.P){ const w=m.wf; V.push(['Mouvements des impayés',g3Bars({title:'Why did it move?',sub:'impayés XOF · '+m.prevLabel+' → '+m.label,labels:['Ouverture','Nouveaux','Aggrav.','Régul.','Rembours.','Clôture'],values:[w.open,w.nouv,w.det,-w.cure,-w.pay,w.close],colors:['#003DA5','#DC2626','#F97316','#16A34A','#22C55E','#C8A951'],w:900,h:380})]); }
    V.push(['Top 10 expositions',g3HBars({title:'Top 10 exposures',sub:'encours XOF',labels:m.top10.map(o=>o.rel),values:m.top10.map(o=>o.enc),color:'#003DA5',w:900})]);
  }catch(e){ console.warn('visuels 3D',e); } return V.filter(v=>v[1]); }
/* ---------- HTML canonique (PDF imprimable et Word) : profondeur réelle (ombres, biseaux, dégradés) ---------- */
function riHtml(m,forWord){ const e=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'})[c]), J=m.jev, T=m.tsL||[];
  const card=c=>forWord?`<td style="width:20%;padding:8px 10px;border-left:4pt solid #${c[5]};border-bottom:2pt solid #A9B8D3;border-right:1pt solid #B8C6DE;background:#F5F9FF"><div style="font-size:7.5pt;color:#334155;font-weight:bold">${e(c[0])}</div><div style="font-size:17pt;font-weight:bold;color:#001B4D">${e(c[1])}</div><div style="font-size:7pt;color:#64748B">${e(c[2])}</div><div style="font-size:8.5pt;font-weight:bold;color:#${riVarC(c[3],c[4])}">${riVar(c[3])}</div></td>`
    :`<div class="card" style="--a:#${c[5]}"><div class="ct">${e(c[0])}</div><div class="cv">${e(c[1])}</div><div class="cu">${e(c[2])}</div><div class="cd" style="color:#${riVarC(c[3],c[4])}">${riVar(c[3])} <span>${m.prevLabel?'vs '+e(m.prevLabel):''}</span></div></div>`;
  const cards=riCards(m), sec=(n,t,s)=>`<h2><b>${n}</b> ${e(t)}<span>${e(s||'')}</span></h2>`;
  const hero=forWord?`${typeof RI_ART!=='undefined'?`<img src="${RI_ART.banner}" width="640" alt="Visuel 3D ECOBANK"/>`:''}<table style="width:100%;border-collapse:collapse"><tr><td style="background:#001B4D;padding:16px 20px;color:#fff"><div style="color:#C8A951;font-size:8pt;font-weight:bold;letter-spacing:3pt">ECOBANK SÉNÉGAL</div><div style="font-size:24pt;font-weight:bold">CREDIT RISK INTELLIGENCE</div><div style="font-size:10pt;color:#C7D7F5">Portfolio Monitoring &amp; Early Warning · Vue Comité des Risques</div></td><td style="background:#003DA5;padding:16px 20px;color:#fff;width:34%"><div style="color:#C8A951;font-size:7.5pt;font-weight:bold">REPORTING DATE</div><div style="font-size:16pt;font-weight:bold">${e(riLong(m.date))}</div><div style="font-size:8pt;font-weight:bold">PORTFOLIO MONITORING</div><div style="font-size:7pt;color:#BFD3FF">${e(m.perimetre)}</div></td></tr><tr><td colspan="2" style="background:#C8A951;height:3px;font-size:2pt">&nbsp;</td></tr></table>`
    :`<div class="hero" style="background:#001B4D url('${typeof RI_ART!=='undefined'?RI_ART.hero:''}') right center/cover"><div><div class="k">E C O B A N K &nbsp; S É N É G A L</div><div class="t">CREDIT RISK INTELLIGENCE</div><div class="s">Portfolio Monitoring &amp; Early Warning · Vue Comité des Risques</div></div><div class="hr"><div class="l">REPORTING DATE</div><div class="d">${e(riLong(m.date))}</div><div class="l2">PORTFOLIO MONITORING</div><div class="p">${e(m.perimetre)}</div></div></div><div class="gold"></div>`;
  const chips=[['PORTFOLIO STATUS',m.watch.some(o=>o.lvl==='CRITICAL')?'VIGILANCE':'STABLE'],['JEV · PD 12M',J?riPct(J.ptf.pd[12].v)+' · '+J.ptf.pd[12].prov.source:'non calibré'],['TYPESAFE',T.length?T.length+' retours · '+T.filter(t=>t.statut==='Revue analyste').length+' en revue':'en attente'],['CONTRÔLES',m.ctl.filter(c=>c.ok).length+' / '+m.ctl.length+' conformes']];
  const chipH=forWord?`<p style="font-size:8pt;color:#334155">${chips.map(c=>'<b style="color:#003DA5">● '+e(c[0])+'</b> '+e(c[1])).join(' &nbsp;&nbsp; ')}</p>`:`<div class="chips">${chips.map(c=>`<div><i></i><b>${e(c[0])}</b> ${e(c[1])}</div>`).join('')}</div>`;
  const tbl=(h,rows,w)=>`<table class="tb" style="width:100%;border-collapse:collapse;font-size:8pt"><tr>${h.map(x=>`<th style="background:#001B4D;color:#fff;padding:5px 6px;text-align:left;border-bottom:2pt solid #C8A951">${e(x)}</th>`).join('')}</tr>${rows.map((r,i)=>`<tr>${r.map(x=>`<td style="padding:4px 6px;border-bottom:1px solid #E2E8F0;background:${i%2?'#F5F9FF':'#fff'}">${x&&x.html?x.html:e(x)}</td>`).join('')}</tr>`).join('')}</table>`;
  const badge=l=>({html:`<span style="background:${l==='WATCH'?'#EAF2FF':'#'+({CRITICAL:RIX.crit,HIGH:RIX.alert,CURED:RIX.ok}[l]||RIX.neu)};color:${l==='WATCH'?'#003DA5':'#fff'};font-weight:bold;padding:1px 6px;border-radius:3px;font-size:7pt">${l}</span>`});
  const wf=m.wf, br=m.P?[['Ouverture',wf.open],['Nouveaux impayés',wf.nouv],['Aggravations',wf.det],['Nouveaux clients',wf.entree],['Régularisations',wf.cure],['Remboursements',wf.pay],['Sorties',wf.sortie],['Clôture',wf.close]]:[];
  const mx=Math.max(1,...br.map(x=>Math.abs(x[1])));
  const story=br.map(([l,v],i)=>`<tr><td style="padding:3px 6px;font-weight:bold;color:#001B4D;width:24%">${e(l)}</td><td style="text-align:right;padding:3px 6px;width:14%;font-weight:bold;color:${i===0||i===7?'#001B4D':!v?'#64748B':v>0?'#DC2626':'#16A34A'}">${i===0||i===7||!v?'':v>0?'+':'−'}${e(riMd(Math.abs(v)))}</td><td style="padding:3px 6px"><div style="height:9px;width:${Math.max(1,100*Math.abs(v)/mx)}%;background:${i===0?'#003DA5':i===7?'#C8A951':v>0?'#DC2626':'#16A34A'};${forWord?'':'box-shadow:0 2px 4px rgba(0,27,77,.3);border-radius:3px'}"></div></td></tr>`).join('');
  const body=`${hero}${chipH}
${sec('01','KEY INDICATORS',m.prevLabel?'vs '+m.prevLabel:'')}${forWord?`<table style="width:100%;border-collapse:separate;border-spacing:6px"><tr>${cards.slice(0,5).map(card).join('')}</tr><tr>${cards.slice(5).map(card).join('')}</tr></table>`:`<div class="cards">${cards.map(card).join('')}</div>`}
${sec('02','WHY DID IT MOVE?','pont des impayés · impayés XOF')}${br.length?`<table style="width:100%;border-collapse:collapse;font-size:8.5pt">${story}</table>`:'<p>Aucun arrêté antérieur en mémoire.</p>'}
${sec('02B','3D VISUALS','visuels en relief')}${(m.vis||(m.vis=riVisuals(m))).map(([t,u])=>forWord?`<img src="${u}" width="620" alt="${e(t)}"/>`:`<img class="v3d" src="${u}" alt="${e(t)}"/>`).join('')}
${sec('03','TOP RISKS','dossiers prioritaires · PD 12M JEV avec provenance')}${tbl(['#','Client','Encours','Impayé','Jours','Stage','Criticité','JEV PD 12M','Orientation TypeSafe','Action'],m.risky.slice(0,12).map((o,i)=>[i+1,o.rel,riMd(o.enc),riMd(o.pdo),o.dj,'S'+o.stage,badge(o.lvl),o.pd12!=null?riPct(o.pd12)+' '+o.pdSrc:'—',o.ts&&o.ts.routage||'—',o.action]))}
${sec('04','RISK ACTION CENTER','par niveau de priorité')}${tbl(['Niveau','Dossiers','Exposition XOF','Avancement moyen','En retard'],['CRITICAL','HIGH','WATCH','CURED'].map(L=>{ const l=L==='CURED'?m.cured:m.watch.filter(o=>o.lvl===L); return [badge(L),l.length,riMd(l.reduce((s,o)=>s+(L==='CURED'&&o.p?o.p.pdo:o.enc),0)),riPct(l.length?l.reduce((s,o)=>s+o.prog,0)/l.length:0,0),l.filter(o=>o.cible&&o.cible<m.date&&o.prog<1).length]; }))}
${sec('05','INSIGHTS','calculés sur les données de l\'arrêté')}${forWord?m.ins.map(x=>`<p style="margin:6px 0"><b style="color:#C8A951;font-size:14pt">${x.n}</b> <b style="color:#334155">${e(x.t)}</b> — <b style="color:#${x.c}">${e(x.big)}</b><br/><span style="font-size:8.5pt;color:#334155">${e(x.p)}</span></p>`).join(''):`<div class="ins">${m.ins.map(x=>`<div style="--a:#${x.c}"><b>${x.n}</b><i>${e(x.t)}</i><strong>${e(x.big)}</strong><p>${e(x.p)}</p></div>`).join('')}</div>`}
${sec('06','JEV & TYPESAFE','probabilités avec provenance · jugements sans chiffres')}${J?`<p style="font-size:8.5pt"><b>JEV · PD 12M (sains) : ${riPct(J.ptf.pd[12].v)}</b> — ${e(jevLbl(J.ptf.pd[12].prov))}${J.ptf.pd[12].prov.avertissement?'<br/><b style="color:#92400E">⚠ '+e(J.ptf.pd[12].prov.avertissement)+'</b>':''}<br/>Scénario sévère : ${e(riMd(J.scen[2].esp))} XOF d'entrées en douteux attendues à 12 mois (SIMULATED).</p>${J.adv?`<p style="font-size:8.5pt"><b>Analyses avancées</b> — temps moyen avant défaut (sain) : ${J.adv.ttd?J.adv.ttd[0].toFixed(0):'—'} mois · guérison 31-60 j : ${riPct(J.adv.cure[0])} · 61-90 j : ${riPct(J.adv.cure[1])} · PD 12M IC 90 % : ${riPct(J.adv.boot.lo)} – ${riPct(J.adv.boot.hi)} (SIMULATED)${J.adv.back?' · backtest : '+J.adv.back.exp.toFixed(1)+' prévues / '+J.adv.back.obs+' observées':''} · stress inverse : ×${J.adv.rev.factor.toFixed(2)} double la PD.</p>`:''}`:'<p>JEV non calibré.</p>'}
${m.scen&&m.scen.length?tbl(['Stress narratif · scénario','Dossiers','Encours exposé','Entrées douteux · base','· sous stress ×2'],m.scen.map(x=>[x.l,x.n,riMd(x.enc),riMd(x.base),riMd(x.str)])):''}
${m.paires&&m.paires.some(p=>p.score>=1||(p.pNom||0)>=0.6)?tbl(['Bénéficiaires potentiellement liés','','Lien (0-2)','Même famille','Lecture','Encours cumulé'],m.paires.filter(p=>p.score>=1||(p.pNom||0)>=0.6).map(p=>[p.a,p.b,p.score.toFixed(2),p.pNom!=null?riPct(p.pNom,0):'—',p.score>=1.1&&(p.pNom||0)>=0.6?'Lien probable':'À vérifier',riMd(p.enc)])):''}
${T.length?tbl(['Référence','Motif','Confiance','Urgence','Orientation','Statut retenu','Revue / contrôles'],T.slice(0,30).map(t=>[t.ref,(typeof TS_MOTIF!=='undefined'&&TS_MOTIF[t.motif])||t.motif||'—',t.cMotif!=null?Math.round(100*t.cMotif)+' %':'',t.urg!=null?t.urg+' / 4':'',t.routage||'',t.statut,(t.revue||[]).concat(t.qc||[]).join(' · ')])):'<p style="font-size:8.5pt">TypeSafe : en attente d\'enrichissement (lot à traiter sur le poste connecté).</p>'}
<p style="font-size:7.5pt;color:#64748B">Méthodologie : montants, classes BCEAO / IFRS 9 / ACTE 7 calculés par APEX ; TypeSafe (jev-latest) ne rend que des jugements, confiance faible → revue analyste ; JEV : chaque probabilité porte sa provenance (OBSERVED, EMPIRICAL, MARKOV, EXPERT, STRESS, SIMULATED, HYBRID). Contrôles : ${m.ctl.map(c=>(c.ok?'✔ ':'✖ ')+e(c.l)).join(' · ')}.</p>`;
  if(forWord) return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>Credit Risk Intelligence</title><style>h2{font-family:'Segoe UI';color:#001B4D;font-size:13pt;border-bottom:1.5pt solid #C8A951;margin-top:14pt}h2 b{color:#C8A951}h2 span{font-size:8pt;color:#64748B;font-weight:normal;font-style:italic;margin-left:8pt}body{font-family:'Segoe UI'}</style></head><body>${body}</body></html>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>Credit Risk Intelligence — ${e(m.label)}</title><style>
@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}body{font-family:'Segoe UI',system-ui,sans-serif;color:#0F172A;margin:0;background:#fff}
.hero{display:grid;grid-template-columns:64% 36%;border-radius:14px;overflow:hidden;box-shadow:0 14px 30px -12px rgba(0,27,77,.55)}.hero>div:first-child{background:linear-gradient(90deg,rgba(0,27,77,.97),rgba(0,40,120,.72));padding:22px 28px;color:#fff}.hero .k{color:#C8A951;font-size:9px;font-weight:700}.hero .t{font-size:34px;font-weight:800;text-shadow:0 3px 8px rgba(0,0,0,.45)}.hero .s{color:#C7D7F5;font-size:13px}
.hr{background:linear-gradient(90deg,rgba(0,27,77,.45),rgba(0,61,165,.05));padding:22px 24px;color:#fff}.hr .l,.hr .l2{color:#C8A951;font-size:9px;font-weight:700}.hr .l2{color:#E0EAFF;margin-top:6px}.hr .d{font-size:22px;font-weight:800;text-shadow:0 2px 6px rgba(0,0,0,.4)}.hr .p{font-size:9px;color:#BFD3FF}
.gold{height:3px;background:linear-gradient(90deg,#C8A951,#F3E7BF);margin:6px 0 10px;border-radius:2px}.chips{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:6px}.chips div{font-size:10px;border:1px solid #DBE6F7;border-radius:10px;padding:6px 10px;box-shadow:0 4px 10px -6px rgba(0,27,77,.35)}.chips i{display:inline-block;width:8px;height:8px;border-radius:50%;background:#2563EB;margin-right:6px}.chips b{color:#64748B;font-size:8.5px;margin-right:4px}
h2{font-size:15px;color:#001B4D;border-bottom:1px solid #C8A951;padding-bottom:3px;margin:16px 0 8px}h2 b{color:#C8A951;margin-right:6px}h2 span{font-size:10px;color:#64748B;font-weight:400;font-style:italic;margin-left:10px}
.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.card{border-radius:12px;padding:10px 12px;background:linear-gradient(180deg,#fff,#EAF2FF);border-left:5px solid var(--a);box-shadow:0 10px 22px -10px rgba(0,27,77,.45),inset 0 1px 0 #fff}.card:nth-child(1),.card:nth-child(10){background:linear-gradient(135deg,#003DA5,#2563EB);color:#fff}.card:nth-child(1) .cv,.card:nth-child(10) .cv{color:#fff;text-shadow:0 2px 6px rgba(0,0,0,.35)}
.ct{font-size:9px;font-weight:700;color:#334155}.card:nth-child(1) .ct,.card:nth-child(10) .ct,.card:nth-child(1) .cu,.card:nth-child(10) .cu{color:#DCE7FF}.cv{font-size:24px;font-weight:800;color:#001B4D;text-shadow:0 2px 3px rgba(0,27,77,.18)}.cu{font-size:9px;color:#64748B}.cd{font-size:11px;font-weight:700}.cd span{font-weight:400;font-style:italic;font-size:9px;color:#64748B}
.v3d{width:49%;margin:0 0.5% 10px;border-radius:14px;box-shadow:0 14px 26px -12px rgba(0,27,77,.5);break-inside:avoid}.tb{border-radius:10px;overflow:hidden;box-shadow:0 8px 18px -10px rgba(0,27,77,.35)}.ins{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.ins>div{border:1px solid #DBE6F7;border-top:5px solid var(--a);border-radius:12px;padding:10px 14px;box-shadow:0 10px 22px -12px rgba(0,27,77,.4);break-inside:avoid}.ins b{color:#C8A951;font-size:26px;font-weight:800;margin-right:10px}.ins i{font-style:normal;font-weight:700;font-size:10px;color:#334155}.ins strong{display:block;font-size:17px;color:var(--a)}.ins p{font-size:10px;color:#334155;margin:4px 0 0}
h2{break-after:avoid}table{break-inside:auto}tr{break-inside:avoid}</style></head><body>${body}</body></html>`; }

/* ---------- PDF : impression de l'HTML canonique (identique aux chiffres Excel) ---------- */
async function riPdf(m){ m=m||await riModel(); const f=document.createElement('iframe'); f.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0;opacity:0'; document.body.appendChild(f);
  f.srcdoc=riHtml(m,false); await new Promise(r=>f.onload=r); EXPORT_AGENT.note('PDF','Credit_Risk_Intelligence (impression)',{ok:true,steps:['HTML canonique','A4 paysage','ombres et dégradés imprimés']});
  setTimeout(()=>{ try{ f.contentWindow.focus(); f.contentWindow.print(); }catch(e){ toast('Impression impossible : '+e.message); } setTimeout(()=>f.remove(),60000); },300); return f; }
/* ---------- Word : HTML Word → .docx (pmHtmlToDocx + couverture premium via pmFinish) ---------- */
async function riDocx(m){ m=m||await riModel(); dcDl(new Blob(['﻿'+riHtml(m,true)],{type:'application/msword'}),'ECOBANK_Credit_Risk_Intelligence_'+dcStamp()+'.doc'); }
/* ---------- PowerPoint natif : cartes en relief (ombres portées réelles), graphiques natifs ---------- */
async function riPptx(m){ m=m||await riModel(); const P=new PptxGenJS(); P.layout='LAYOUT_WIDE'; P.title='Credit Risk Intelligence — '+m.label; const W=13.333, H=7.5, F='Segoe UI';
  const SHf=()=>({type:'outer',blur:8,offset:4,angle:90,color:'001B4D',opacity:0.35}), J=m.jev, T=m.tsL||[];
  const head=(s,t,sub)=>{ s.background={color:'FFFFFF'}; if(typeof RI_ART!=='undefined'&&RI_ART.banner){ s.addImage({data:RI_ART.banner,x:0,y:0,w:W,h:W*560/2400,sizing:{type:'cover',w:W,h:0.9}}); s.addShape(P.ShapeType.rect,{x:0,y:0,w:W*0.7,h:0.9,fill:{color:RIX.deep,transparency:15},line:{color:RIX.deep,transparency:100}}); } else s.addShape(P.ShapeType.rect,{x:0,y:0,w:W,h:0.9,fill:{color:RIX.deep}}); s.addShape(P.ShapeType.rect,{x:0,y:0.9,w:W,h:0.04,fill:{color:RIX.gold},line:{color:RIX.gold}});
    s.addText([{text:'◆ ECOBANK SÉNÉGAL   ',options:{color:RIX.gold,bold:true,fontSize:10}},{text:t,options:{color:'FFFFFF',bold:true,fontSize:20}}],{x:0.4,y:0.12,w:9.5,h:0.66,fontFace:F,margin:0,shadow:{type:'outer',blur:4,offset:2,angle:90,color:'000000',opacity:0.5}});
    s.addText(sub||'',{x:9.4,y:0.2,w:3.6,h:0.5,fontFace:F,fontSize:9,color:'BFD3FF',align:'right'}); s.addText(m.label+' · INTERNAL USE ONLY',{x:0.4,y:7.1,w:6,h:0.3,fontFace:F,fontSize:8,color:RIX.neu}); };
  // 1 · couverture héro
  let s=P.addSlide(); s.background={color:RIX.deep}; const ART=typeof RI_ART!=='undefined'?RI_ART:null; if(ART&&ART.hero) s.addImage({data:ART.hero,x:0,y:0,w:W,h:H}); s.addShape(P.ShapeType.rect,{x:0,y:0,w:W*0.6,h:H,fill:{color:RIX.deep,transparency:ART?18:0},line:{color:RIX.deep,transparency:100}}); if(!ART) s.addShape(P.ShapeType.rect,{x:W*0.64,y:0,w:W*0.36,h:H,fill:{color:RIX.eb}});
  s.addShape(P.ShapeType.ellipse,{x:9.6,y:-1.6,w:5,h:5,fill:{color:RIX.bright,transparency:70},line:{color:RIX.bright,transparency:100}});
  s.addText('E C O B A N K   S É N É G A L',{x:0.7,y:1.6,w:7.5,h:0.4,fontFace:F,fontSize:12,bold:true,color:RIX.gold});
  s.addText('CREDIT RISK\nINTELLIGENCE',{x:0.7,y:2.0,w:7.8,h:2.0,fontFace:F,fontSize:44,bold:true,color:'FFFFFF',shadow:{type:'outer',blur:6,offset:3,angle:90,color:'000000',opacity:0.45}});
  s.addText('Portfolio Monitoring & Early Warning · Vue Comité des Risques',{x:0.7,y:4.1,w:7.8,h:0.5,fontFace:F,fontSize:14,color:'C7D7F5'});
  s.addShape(P.ShapeType.rect,{x:0.7,y:4.75,w:5.5,h:0.04,fill:{color:RIX.gold},line:{color:RIX.gold}});
  s.addText([{text:'REPORTING DATE\n',options:{fontSize:10,bold:true,color:RIX.gold}},{text:riLong(m.date)+'\n',options:{fontSize:24,bold:true,color:'FFFFFF'}},{text:'PORTFOLIO MONITORING\n',options:{fontSize:11,bold:true,color:'E0EAFF'}},{text:m.perimetre,options:{fontSize:9,color:'BFD3FF'}}],{x:8.9,y:2.6,w:4.2,h:2.6,fontFace:F,valign:'middle'});
  // 2 · indicateurs : cartes en relief
  s=P.addSlide(); head(s,'KEY INDICATORS',m.prevLabel?'vs '+m.prevLabel:'');
  riCards(m).forEach((c,i)=>{ const x=0.4+(i%5)*2.55, y=1.35+Math.floor(i/5)*2.75, dark=i===0||i===9;
    s.addShape(P.ShapeType.roundRect,{x,y,w:2.35,h:2.45,rectRadius:0.12,fill:{color:dark?RIX.eb:'FFFFFF'},line:{color:dark?RIX.eb:RIX.line,width:0.75},shadow:SHf()});
    s.addShape(P.ShapeType.rect,{x,y:y+0.15,w:0.07,h:2.15,fill:{color:c[5]},line:{color:c[5]}});
    s.addText(c[0],{x:x+0.2,y:y+0.15,w:2.05,h:0.35,fontFace:F,fontSize:9,bold:true,color:dark?'DCE7FF':RIX.ink2});
    s.addText(c[1],{x:x+0.2,y:y+0.55,w:2.1,h:0.8,fontFace:F,fontSize:24,bold:true,color:dark?'FFFFFF':RIX.deep,shadow:{type:'outer',blur:3,offset:2,angle:90,color:'001B4D',opacity:0.25}});
    s.addText(c[2],{x:x+0.2,y:y+1.35,w:2.1,h:0.4,fontFace:F,fontSize:8.5,color:dark?'DCE7FF':RIX.neu});
    s.addText(riVar(c[3]),{x:x+0.2,y:y+1.8,w:2.1,h:0.4,fontFace:F,fontSize:11,bold:true,color:dark&&c[3]==null?'DCE7FF':riVarC(c[3],c[4])}); });
  // 3 · tendance et distribution
  s=P.addSlide(); head(s,'PORTFOLIO TREND & RISK DISTRIBUTION','');
  const labs=m.months.map(x=>x.label.slice(0,5));
  s.addShape(P.ShapeType.roundRect,{x:0.4,y:1.2,w:8.1,h:5.7,rectRadius:0.1,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()});
  s.addChart(P.ChartType.line,[{name:'Impayés',labels:labs,values:m.months.map(x=>x.k.pdo)},{name:'Stage 2',labels:labs,values:m.months.map(x=>x.k.s2)},{name:'Stage 3',labels:labs,values:m.months.map(x=>x.k.s3)}],{x:0.6,y:1.4,w:7.7,h:5.3,chartColors:[RIX.cyan,RIX.gold,RIX.crit],lineSize:3,lineDataSymbolSize:7,showLegend:true,legendPos:'b',legendFontFace:F,catAxisLabelFontFace:F,valAxisLabelFontFace:F,valAxisLabelFormatCode:'#,##0,,," Md"',valGridLine:{color:'E2E8F0',style:'dash',size:0.5},catAxisLabelColor:RIX.neu,valAxisLabelColor:RIX.neu,shadow:{type:'outer',blur:4,offset:2,angle:90,color:'001B4D',opacity:0.3}});
  s.addShape(P.ShapeType.roundRect,{x:8.8,y:1.2,w:4.1,h:5.7,rectRadius:0.1,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()});
  s.addChart(P.ChartType.doughnut,[{name:'Stages',labels:['Stage 1','Stage 2','Stage 3'],values:[m.K.enc-m.K.s2-m.K.s3,m.K.s2,m.K.s3]}],{x:9,y:1.4,w:3.7,h:5.3,holeSize:62,chartColors:[RIX.eb,RIX.gold,RIX.crit],showPercent:true,showLegend:true,legendPos:'b',legendFontFace:F,dataLabelColor:'FFFFFF',dataLabelFontBold:true,shadow:{type:'outer',blur:6,offset:3,angle:90,color:'001B4D',opacity:0.35}});
  // 4 · pont des impayés (cascade)
  if(m.P){ s=P.addSlide(); head(s,'WHY DID IT MOVE?','pont des impayés '+m.prevLabel+' → '+m.label); const w=m.wf;
    const st=[['Ouverture',w.open,'t',RIX.eb],['Nouveaux impayés',w.nouv,'d',RIX.crit],['Aggravations',w.det,'d',RIX.alert],['Nouveaux clients',w.entree,'d',RIX.cyan],['Régularisations',w.cure,'d',RIX.ok],['Remboursements',w.pay,'d','22C55E'],['Sorties',w.sortie,'d',RIX.cyan],['Clôture',w.close,'t',RIX.gold]].filter(x=>x[2]==='t'||Math.abs(x[1])>0);
    let run=0; const base=[],val=[]; st.forEach(([l,v,t])=>{ if(t==='t'){ base.push(0); val.push(v); run=v; } else { base.push(Math.min(run,run+v)); val.push(Math.abs(v)); run+=v; } });
    s.addShape(P.ShapeType.roundRect,{x:0.4,y:1.2,w:12.5,h:5.7,rectRadius:0.1,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()});
    s.addChart(P.ChartType.bar3d,[{name:'base',labels:st.map(x=>x[0]),values:base},{name:'Mouvement',labels:st.map(x=>x[0]),values:val}],{x:0.6,y:1.4,w:12.1,h:5.3,barGrouping:'stacked',barGapWidthPct:45,v3DRotX:8,v3DRotY:12,v3DRAngAx:true,chartColors:['FFFFFF',RIX.eb],showLegend:false,valAxisHidden:true,valGridLine:{style:'none'},catAxisLabelFontFace:F,catAxisLabelColor:RIX.ink2,showValue:false});
    st.forEach(([l,v,t,c],i)=>s.addText((t==='t'||!v?'':v>0?'+':'−')+riMd(Math.abs(v)),{x:0.9+i*(11.4/st.length),y:1.3,w:11.4/st.length,h:0.4,fontFace:F,fontSize:11,bold:true,color:c===RIX.gold?RIX.deep:c,align:'center'})); }
  // 4 bis · visuels 3D
  { const V=m.vis||(m.vis=riVisuals(m)); if(V.length){ s=P.addSlide(); head(s,'3D VISUALS','visuels en relief'); V.slice(0,4).forEach(([t,u],i)=>s.addImage({data:u,x:0.4+(i%2)*6.35,y:1.15+Math.floor(i/2)*3.0,w:6.1,h:2.85})); } }
  // 5 · top risques + action center
  s=P.addSlide(); head(s,'TOP RISKS & RISK ACTION CENTER','');
  m.risky.slice(0,6).forEach((o,i)=>{ const y=1.25+i*0.95, L=RI_LVL[o.lvl];
    s.addShape(P.ShapeType.roundRect,{x:0.4,y,w:8.2,h:0.82,rectRadius:0.08,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()});
    s.addText('#'+String(i+1).padStart(2,'0'),{x:0.5,y,w:0.8,h:0.82,fontFace:F,fontSize:18,bold:true,color:RIX.gold});
    s.addText([{text:o.rel+'\n',options:{bold:true,fontSize:12,color:RIX.deep}},{text:riMd(o.enc)+' XOF · '+o.dj+' j · Stage '+o.stage+(o.pd12!=null?' · JEV PD 12M '+riPct(o.pd12)+' ('+o.pdSrc+')':'')+(o.ts&&o.ts.routage?' · → '+o.ts.routage:''),options:{fontSize:9,color:RIX.ink2}}],{x:1.3,y,w:5.6,h:0.82,fontFace:F,valign:'middle'});
    s.addShape(P.ShapeType.roundRect,{x:7.0,y:y+0.22,w:1.4,h:0.38,rectRadius:0.06,fill:{color:o.lvl==='WATCH'?RIX.light:L.c},line:{color:o.lvl==='WATCH'?'BFD3FF':L.c},shadow:{type:'outer',blur:3,offset:1.5,angle:90,color:'000000',opacity:0.3}});
    s.addText(L.t,{x:7.0,y:y+0.22,w:1.4,h:0.38,fontFace:F,fontSize:9,bold:true,color:o.lvl==='WATCH'?RIX.eb:'FFFFFF',align:'center'}); });
  ['CRITICAL','HIGH','WATCH','CURED'].forEach((Lk,i)=>{ const l=Lk==='CURED'?m.cured:m.watch.filter(o=>o.lvl===Lk), L=RI_LVL[Lk], y=1.25+i*1.42, done=l.length?l.reduce((s2,o)=>s2+o.prog,0)/l.length:0;
    s.addShape(P.ShapeType.roundRect,{x:8.9,y,w:4.0,h:1.25,rectRadius:0.1,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()});
    s.addShape(P.ShapeType.roundRect,{x:9.05,y:y+0.15,w:1.05,h:0.95,rectRadius:0.08,fill:{color:Lk==='WATCH'?RIX.eb:L.c},line:{color:Lk==='WATCH'?RIX.eb:L.c}});
    s.addText(String(l.length),{x:9.05,y:y+0.15,w:1.05,h:0.95,fontFace:F,fontSize:22,bold:true,color:'FFFFFF',align:'center'});
    s.addText([{text:L.t+'  ',options:{bold:true,fontSize:11,color:Lk==='WATCH'?RIX.eb:L.c}},{text:L.fr+'\n',options:{fontSize:9,color:RIX.ink2}},{text:riMd(l.reduce((s2,o)=>s2+(Lk==='CURED'&&o.p?o.p.pdo:o.enc),0))+' XOF',options:{fontSize:9,color:RIX.ink2}}],{x:10.2,y:y+0.1,w:2.6,h:0.7,fontFace:F});
    s.addShape(P.ShapeType.rect,{x:10.25,y:y+0.88,w:2.4,h:0.12,fill:{color:'EEF2F7'},line:{color:'EEF2F7'}}); s.addShape(P.ShapeType.rect,{x:10.25,y:y+0.88,w:Math.max(0.02,2.4*done),h:0.12,fill:{color:Lk==='WATCH'?RIX.eb:L.c},line:{color:Lk==='WATCH'?RIX.eb:L.c}}); });
  // 6 · insights
  s=P.addSlide(); head(s,'INSIGHTS','calculés sur les données');
  m.ins.slice(0,8).forEach((x,i)=>{ const X=0.4+(i%4)*3.18, Y=1.25+Math.floor(i/4)*2.95;
    s.addShape(P.ShapeType.roundRect,{x:X,y:Y,w:2.98,h:2.75,rectRadius:0.1,fill:{color:'FFFFFF'},line:{color:RIX.line},shadow:SHf()}); s.addShape(P.ShapeType.rect,{x:X,y:Y,w:2.98,h:0.08,fill:{color:x.c},line:{color:x.c}});
    s.addText(x.n,{x:X+0.15,y:Y+0.15,w:0.9,h:0.6,fontFace:F,fontSize:26,bold:true,color:RIX.gold});
    s.addText(x.t,{x:X+1.0,y:Y+0.2,w:1.9,h:0.5,fontFace:F,fontSize:9,bold:true,color:RIX.ink2});
    s.addText(x.big,{x:X+0.15,y:Y+0.8,w:2.7,h:0.5,fontFace:F,fontSize:15,bold:true,color:x.c===RIX.gold?RIX.deep:x.c});
    s.addText(x.p,{x:X+0.15,y:Y+1.3,w:2.7,h:1.35,fontFace:F,fontSize:8,color:RIX.ink2,valign:'top'}); });
  // 7 · couche TypeSafe & JEV
  s=P.addSlide(); head(s,'COUCHE TYPESAFE & JEV','jugements sans chiffres · probabilités avec provenance');
  s.addShape(P.ShapeType.roundRect,{x:0.4,y:1.2,w:12.5,h:1.2,rectRadius:0.1,fill:{color:RIX.light},line:{color:'BFD3FF'},shadow:SHf()});
  s.addText([{text:'JEV · PD 12M (sains) : '+(J?riPct(J.ptf.pd[12].v):'non calibré')+'\n',options:{bold:true,fontSize:16,color:RIX.eb}},{text:J?jevLbl(J.ptf.pd[12].prov)+(J.ptf.pd[12].prov.avertissement?'  ·  ⚠ '+J.ptf.pd[12].prov.avertissement:''):'',options:{fontSize:9,color:RIX.ink2}},{text:J&&J.adv?'\nAnalyses avancées : avant défaut '+(J.adv.ttd?J.adv.ttd[0].toFixed(0):'—')+' mois · guérison 31-60 j '+riPct(J.adv.cure[0])+' · IC 90 % '+riPct(J.adv.boot.lo)+' – '+riPct(J.adv.boot.hi)+' · stress inverse ×'+J.adv.rev.factor.toFixed(2):'',options:{fontSize:9,color:RIX.eb,bold:true}}],{x:0.6,y:1.25,w:12.1,h:1.1,fontFace:F});
  const rows=[[{text:'Référence',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Motif',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Confiance',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Urgence',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Orientation',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Statut retenu',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}}]]
    .concat(T.slice(0,11).map(t=>[t.ref,(typeof TS_MOTIF!=='undefined'&&TS_MOTIF[t.motif])||t.motif||'—',t.cMotif!=null?Math.round(100*t.cMotif)+' %':'',t.urg!=null?t.urg+' / 4':'',t.routage||'',{text:t.statut||'',options:{bold:true,color:t.statut==='Revue analyste'?RIX.crit:RIX.eb}}].map(v=>typeof v==='object'?v:{text:String(v)})));
  if(T.length) s.addTable(rows,{x:0.4,y:2.65,w:12.5,fontFace:F,fontSize:9,color:RIX.ink,border:{type:'solid',color:'E2E8F0',pt:0.5},fill:{color:'FFFFFF'},rowH:0.33});
  else s.addText('TypeSafe : en attente d\'enrichissement. Exporter le lot depuis la salle JEV, l\'enrichir sur le poste connecté, puis recharger le classeur retourné.',{x:0.4,y:2.8,w:12.5,h:0.8,fontFace:F,fontSize:12,color:RIX.ink2});
  // 7 bis · stress narratif
  if(m.scen&&m.scen.length){ s=P.addSlide(); head(s,'STRESS NARRATIF · SCÉNARIOS MACRO','exposition jugée · montants calculés');
    s.addChart(P.ChartType.bar3d,[{name:'Encours exposé',labels:m.scen.map(x=>x.l),values:m.scen.map(x=>x.enc)}],{x:0.4,y:1.2,w:6.4,h:5.6,barDir:'bar',v3DRotX:8,v3DRotY:12,v3DRAngAx:true,catAxisOrientation:'maxMin',chartColors:[RIX.alert],catAxisLabelFontFace:F,valAxisHidden:true,valGridLine:{style:'none'},showValue:false,showLegend:false});
    s.addTable([[{text:'Scénario',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Dossiers',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Encours',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Douteux attendus · stress',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}}]].concat(m.scen.map(x=>[{text:x.l},{text:String(x.n)},{text:riMd(x.enc)},{text:riMd(x.base)+' → '+riMd(x.str),options:{bold:true,color:RIX.crit}}])),{x:7.0,y:1.3,w:5.9,fontFace:F,fontSize:9,border:{type:'solid',color:'E2E8F0',pt:0.5},rowH:0.42}); }
  // 8 · audit
  s=P.addSlide(); head(s,'AUDIT · CONTRÔLES AUTOMATIQUES','source canonique unique');
  s.addTable([[{text:'Contrôle',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}},{text:'Résultat',options:{bold:true,color:'FFFFFF',fill:{color:RIX.deep}}}]].concat(m.ctl.map(c=>[{text:c.l},{text:c.ok?'✔ CONFORME':'✖ ÉCART',options:{bold:true,color:c.ok?RIX.ok:RIX.crit,fill:{color:c.ok?'DCFCE7':'FEE2E2'}}}])),{x:0.4,y:1.3,w:12.5,colW:[9.5,3.0],fontFace:F,fontSize:10,border:{type:'solid',color:'E2E8F0',pt:0.5},rowH:0.42});
  const blob=await P.write({outputType:'blob'}); dcDl(blob,'ECOBANK_Credit_Risk_Intelligence_'+dcStamp()+'.pptx'); return blob; }

/* =====================================================================
   AGENT EXPORT — orchestre tous les exports (Excel, Word, PowerPoint, PDF),
   applique le format de référence, contrôle et journalise ; ses règles
   s'enrichissent à chaque export (journal local + suggestions).
   ===================================================================== */
const EXPORT_AGENT={ key:'apex_export_agent_v1', log:[],
  load(){ try{ this.log=JSON.parse(localStorage.getItem(this.key)||'[]'); }catch(e){ this.log=[]; } },
  save(){ try{ localStorage.setItem(this.key,JSON.stringify(this.log.slice(-300))); }catch(e){} },
  note(type,name,o){ const e={t:new Date().toISOString(),type,name,ok:o.ok!==false,size:o.size||0,ms:o.ms||0,steps:o.steps||[],warn:o.warn||[]}; this.log.push(e); this.save(); return e; },
  async inspect(blob,name){ const w=[]; try{ const z=await JSZip.loadAsync(await blob.arrayBuffer(),{createFolders:false}); const files=Object.keys(z.files);
      const xml=(await Promise.all(files.filter(f=>/\.xml$/.test(f)).slice(0,400).map(f=>z.file(f).async('string')))).join('');
      if(/NaN|Infinity|undefined/.test(xml.replace(/<c:f>[^<]*<\/c:f>/g,''))) w.push('valeur NaN / Infinity / undefined détectée');
      if(/#REF!|#VALUE!|#DIV\/0!/.test(xml)) w.push('erreur de formule (#REF!, #VALUE!, #DIV/0!)');
      const old=(xml.match(/00415E|005C83|8CC63F/gi)||[]).length; if(old) w.push(old+' couleur(s) de l\'ancienne charte restante(s)');
      if(/\.xlsx$/i.test(name)&&!/TypeSafe|TYPESAFE|SEMANTIQUE|sémantique|SÉMANTIQUE|APEX-RI/.test(xml+files.join(' '))) w.push('couche d\'analyse sémantique absente');
      if(/TypeSafe|TYPESAFE|\bjev[-_]|\bJEV\b|\bJev\b/.test(xml)) w.push('nom d\'outil interne visible');
      if(blob.size>15e6) w.push('fichier lourd ('+(blob.size/1e6).toFixed(1)+' Mo)');
    }catch(e){ w.push('inspection impossible : '+e.message); } return w; },
  suggestions(){ const s=[], L=this.log.slice(-100); const by=k=>L.filter(e=>e.warn.some(w=>w.includes(k))).length;
    if(by('TypeSafe')) s.push('Charger les retours TypeSafe (salle JEV → « ⇪ Retours TypeSafe ») : '+by('TypeSafe')+' export(s) sans couche TypeSafe complète.');
    if(by('ancienne charte')) s.push('Des visuels d\'anciennes salles portent encore l\'ancienne charte : les régénérer depuis la dernière version d\'APEX.');
    if(by('lourd')) s.push('Fichiers lourds : préférer les exports Risk Intelligence (données agrégées, aucun visuel image).');
    if(by('NaN')||by('formule')) s.push('Des valeurs invalides ont été détectées : vérifier la source de l\'export concerné dans le journal.');
    if(!s.length) s.push('Aucune anomalie sur les derniers exports : format de référence respecté.'); return s; },
  panel(){ this.load(); let p=document.getElementById('expAgent'); if(p) p.remove(); p=document.createElement('div'); p.id='expAgent';
    p.style.cssText='position:fixed;inset:6% 8%;z-index:500;background:#fff;border-radius:18px;box-shadow:0 30px 70px -20px rgba(0,27,77,.6);display:flex;flex-direction:column;font:13px Segoe UI,system-ui;overflow:hidden';
    const L=this.log.slice().reverse().slice(0,120), e=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'})[c]);
    p.innerHTML=`<div style="background:linear-gradient(90deg,#001B4D,#003DA5,#2563EB);color:#fff;padding:14px 20px;box-shadow:inset 0 -3px 0 #C8A951"><b style="letter-spacing:.08em">AGENT EXPORT</b><span style="margin-left:12px;color:#C7D7F5;font-size:12px">Format de référence ECOBANK VISUAL MASTERING · Excel, Word, PowerPoint, PDF · contrôles et amélioration continue</span><button style="float:right;border:0;background:rgba(255,255,255,.18);color:#fff;border-radius:8px;padding:4px 10px;cursor:pointer" onclick="this.closest('#expAgent').remove()">✕</button></div>
      <div style="padding:14px 20px;background:#F5F9FF;border-bottom:1px solid #DBE6F7"><b style="color:#001B4D">Suggestions d'amélioration</b><ul style="margin:6px 0 0">${this.suggestions().map(x=>'<li>'+e(x)+'</li>').join('')}</ul></div>
      <div style="padding:10px 20px;display:flex;gap:8px;flex-wrap:wrap">${Object.entries(RI_VARIANTS).map(([k,v])=>`<button data-x="${k}" style="border:0;background:#EAF2FF;color:#003DA5;border-radius:9px;padding:7px 11px;font-weight:600;cursor:pointer">Excel · ${e(v.lib)}</button>`).join('')}<button data-d="ppt" style="border:0;background:#003DA5;color:#fff;border-radius:9px;padding:7px 11px;font-weight:600;cursor:pointer">PowerPoint</button><button data-d="doc" style="border:0;background:#003DA5;color:#fff;border-radius:9px;padding:7px 11px;font-weight:600;cursor:pointer">Word</button><button data-d="pdf" style="border:0;background:#C8A951;color:#001B4D;border-radius:9px;padding:7px 11px;font-weight:700;cursor:pointer">PDF</button></div>
      <div style="flex:1;overflow:auto;padding:0 20px 16px"><table style="width:100%;border-collapse:collapse;font-size:12px"><tr style="background:#001B4D;color:#fff"><th style="text-align:left;padding:6px">Date</th><th style="text-align:left">Type</th><th style="text-align:left">Fichier</th><th>Taille</th><th>Durée</th><th style="text-align:left">Étapes</th><th style="text-align:left">Contrôles</th></tr>${L.map((x,i)=>`<tr style="background:${i%2?'#F5F9FF':'#fff'}"><td style="padding:5px">${e(x.t.replace('T',' ').slice(0,19))}</td><td><b>${e(x.type)}</b></td><td>${e(x.name)}</td><td style="text-align:right">${x.size?(x.size/1024).toFixed(0)+' Ko':''}</td><td style="text-align:right">${x.ms?x.ms+' ms':''}</td><td>${e(x.steps.join(' · '))}</td><td style="color:${x.warn.length?'#DC2626':'#16A34A'};font-weight:600">${x.warn.length?e(x.warn.join(' · ')):'✔ conforme'}</td></tr>`).join('')||'<tr><td colspan="7" style="padding:10px;color:#64748B">Aucun export journalisé.</td></tr>'}</table></div>`;
    document.body.appendChild(p); p.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>riExport(b.dataset.x)); p.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>riDoc(b.dataset.d)); } };
EXPORT_AGENT.load();
/* PowerPoint : XML de PptxGenJS remis en conformité (ordre des paragraphes, présentation, courbes) et
   série « base » des cascades rendue invisible (barres 3D flottantes) */
async function pptxFix(blob){ try{ const z=await JSZip.loadAsync(await blob.arrayBuffer(),{createFolders:false}); let hit=0;
    const ed=async(f,fn)=>{ const x=await z.file(f).async('string'), y=fn(x); if(y!==x){ z.file(f,y); hit++; } };
    for(const f of Object.keys(z.files)){
      if(/^ppt\/(slides\/slide|slideLayouts\/slideLayout|slideMasters\/slideMaster|notesSlides\/notesSlide)\d*\.xml$/.test(f))
        await ed(f,x=>x.replace(/<a:p>([\s\S]*?)<\/a:p>/g,(m,inner)=>{ let k=0; return '<a:p>'+inner.replace(/<a:pPr\b(?:[^>]*\/>|[^>]*>[\s\S]*?<\/a:pPr>)/g,(pp,off)=>off===0&&k++===0?pp:'')+'</a:p>'; }));
      else if(f==='ppt/presentation.xml')
        await ed(f,x=>{ const m=x.match(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/); if(!m||x.indexOf('</p:sldMasterIdLst>'+m[0])>=0) return x; return x.replace(m[0],'').replace('</p:sldMasterIdLst>','</p:sldMasterIdLst>'+m[0]); });
      else if(/^ppt\/charts\/chart\d+\.xml$/.test(f))
        await ed(f,x=>{ const def=new Set([...x.matchAll(/<c:(?:catAx|valAx|serAx|dateAx)>\s*<c:axId val="(\d+)"/g)].map(m=>m[1]));
          return x.replace(/<c:lineChart>(?!<c:grouping)/g,'<c:lineChart><c:grouping val="standard"/>')
          .replace(/<c:lineChart>[\s\S]*?<\/c:lineChart>/g,b=>b.replace(/<c:invertIfNegative [^>]*\/>/g,'')
            .replace(/<c:ser>[\s\S]*?<\/c:ser>/g,sr=>{ const mk=sr.match(/<c:marker>[\s\S]*?<\/c:marker>/), dl=sr.match(/<c:dLbls>[\s\S]*?<\/c:dLbls>/); return mk&&dl&&sr.indexOf(dl[0])<sr.indexOf(mk[0])?sr.replace(mk[0],'').replace(dl[0],mk[0]+dl[0]):sr; })
            .replace(/<c:axId val="(\d+)"\/>/g,(m,id)=>def.has(id)?m:''))
          .replace(/(<c:ser>(?:(?!<\/c:ser>)[\s\S])*?<c:v>base<\/c:v>(?:(?!<\/c:ser>)[\s\S])*?)<c:spPr>[\s\S]*?<\/c:spPr>/g,'$1<c:spPr><a:noFill/><a:ln><a:noFill/></a:ln></c:spPr>'); });
    }
    if(!hit) return null; return await z.generateAsync({type:'blob',compression:'DEFLATE',mimeType:blob.type||'application/vnd.openxmlformats-officedocument.presentationml.presentation'}); }catch(e){ console.warn('pptxFix',e); return null; } }
async function riDoc(kind){ try{ toast('⏳ Agent EXPORT : '+({ppt:'PowerPoint',doc:'Word',pdf:'PDF'})[kind]+'…',2500); const m=await riModel(); if(kind==='ppt') await riPptx(m); else if(kind==='doc') await riDocx(m); else await riPdf(m); }catch(e){ console.warn('RI doc',e); toast('❌ '+e.message,5000); } }
/* ---------- couche commune Word / PowerPoint : palette Blue Premium + couche TypeSafe ---------- */
async function pmBlueOffice(blob,name){ try{ const z=await JSZip.loadAsync(await blob.arrayBuffer(),{createFolders:false}), isW=/\.docx$/i.test(name);
    for(const f of Object.keys(z.files)) if(/\.xml$/.test(f)&&/^(word|ppt)\//.test(f)) z.file(f,pmBlueRemap(await z.file(f).async('string')));
    if(isW){ const df=z.file('word/document.xml'); let d=await df.async('string');
      if(!/COUCHE TYPESAFE/.test(d)){ const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'), par=(t,o)=>`<w:p><w:pPr>${o.br?'<w:pBdr><w:bottom w:val="single" w:sz="8" w:space="2" w:color="C8A951"/></w:pBdr>':''}<w:spacing w:before="${o.b||60}" w:after="60"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Segoe UI" w:hAnsi="Segoe UI"/>${o.bold?'<w:b/>':''}<w:color w:val="${o.c||'334155'}"/><w:sz w:val="${o.sz||18}"/></w:rPr><w:t xml:space="preserve">${esc(t)}</w:t></w:r></w:p>`;
        const rows=pmTsRows(); const xml=par('COUCHE TYPESAFE & JEV',{bold:1,c:'001B4D',sz:26,b:360,br:1})+rows.slice(1).map(r=>r.t==='hdr'?'':par(r.v.filter(Boolean).join('  ·  '),{bold:r.t==='kpi'||r.rv,c:r.rv?'DC2626':r.t==='warn'?'92400E':r.t==='kpi'?'003DA5':'334155',sz:r.t==='row'?16:18})).join('');
        d=d.replace(/(<w:sectPr[\s\S]*?<\/w:sectPr>\s*<\/w:body>)/,xml+'$1'); }
      // texte en relief : ombre portée Word 2010 sur les titres et les grands chiffres (gras ≥ 13 pt)
      const W14='http://schemas.microsoft.com/office/word/2010/wordml', MC='http://schemas.openxmlformats.org/markup-compatibility/2006';
      if(!/xmlns:w14=/.test(d.slice(0,3000))) d=d.replace('<w:document ','<w:document xmlns:w14="'+W14+'" ');
      if(!/xmlns:mc=/.test(d.slice(0,3000))) d=d.replace('<w:document ','<w:document xmlns:mc="'+MC+'" ');
      if(/mc:Ignorable="/.test(d.slice(0,3000))){ if(!/mc:Ignorable="[^"]*\bw14\b/.test(d.slice(0,3000))) d=d.replace(/mc:Ignorable="/,'mc:Ignorable="w14 '); } else d=d.replace('<w:document ','<w:document mc:Ignorable="w14" ');
      const SHD='<w14:shadow w14:blurRad="38100" w14:dist="19050" w14:dir="5400000" w14:sx="100000" w14:sy="100000" w14:kx="0" w14:ky="0" w14:algn="tl"><w14:srgbClr w14:val="001B4D"><w14:alpha w14:val="62000"/></w14:srgbClr></w14:shadow>';
      d=d.replace(/<w:rPr>((?:(?!<\/w:rPr>)[\s\S])*?<w:b\/>(?:(?!<\/w:rPr>)[\s\S])*?<w:sz w:val="(\d+)"\/>(?:(?!<\/w:rPr>)[\s\S])*?)<\/w:rPr>/g,(m0,inner,sz)=>+sz>=26&&!/w14:shadow/.test(inner)?'<w:rPr>'+inner+SHD+'</w:rPr>':m0);
      df&&z.file('word/document.xml',d); }
    return await z.generateAsync({type:'blob',compression:'DEFLATE',mimeType:isW?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/vnd.openxmlformats-officedocument.presentationml.presentation'});
  }catch(e){ console.warn('Blue Premium Office',e); return null; } }

/* ---------- nettoyage final de tout export : les noms des outils internes n'apparaissent jamais ---------- */
const EXP_NAMES=[[/\s*\((?:JEV|TypeSafe|TYPESAFE)\)/g,''],[/JEV OUTLOOK/g,'RISK OUTLOOK'],[/Méthodologie TypeSafe/g,'Méthodologie analyse sémantique'],[/_TYPESAFE/g,'_SEMANTIQUE'],[/TYPESAFE/g,'ANALYSE SÉMANTIQUE'],[/TypeSafe/g,'Analyse sémantique'],[/typesafe/g,'analyse sémantique'],[/jev-latest/gi,'moteur sémantique'],[/\bjev-preview\b/gi,'moteur sémantique (préversion)'],[/\bjev-(\d[\w.]*)/gi,'moteur sémantique v$1'],[/\bjev\b/g,'moteur sémantique'],[/\bJEV\b/g,'RISK OUTLOOK'],[/\bJev\b/g,'Risk Outlook']];
const expScrubTxt=s=>String(s).split(/(data:[^;,"')\s]+;base64,[A-Za-z0-9+\/=]+)/).map((p,i)=>i%2?p:EXP_NAMES.reduce((a,[r,b])=>a.replace(r,b),p)).join('');
async function expScrub(blob,name){ try{ if(!/\.(xlsx|docx|pptx)$/i.test(name)) return null; const z=await JSZip.loadAsync(await blob.arrayBuffer(),{createFolders:false}); let hit=false;
    for(const f of Object.keys(z.files)){ if(!/\.xml$/.test(f)||/Content_Types/.test(f)) continue; const x=await z.file(f).async('string'), y=expScrubTxt(x); if(y!==x){ hit=true; z.file(f,y); } }
    if(!hit) return null; return await z.generateAsync({type:'blob',compression:'DEFLATE',mimeType:blob.type||'application/octet-stream'}); }catch(e){ console.warn('scrub',e); return null; } }
/* recalibrage automatique de Risk Outlook (JEV) à chaque arrêté chargé : mémoire des arrêtés + données du jour */
async function jevAuto(){ try{ await new Promise(r=>setTimeout(r,1200)); if(!S.arrete||typeof jevHistorique!=='function') return; const T=+S.arrete; const {H}=await jevHistorique(T,()=>{}); if(!H.length) return;
    JEV.res=jevRun(H); JEV.key=T+'|'+(S.meta&&S.meta.file||'')+'|'+TSX.n+'|'+(TSX.src&&TSX.src.date||''); const ov=document.getElementById('jevRoom'); if(ov&&ov.classList.contains('on')){ jevFillDates(); jevRender(); jevSt('✔ '+H.length+' arrêté(s) mensuel(s) · calibration au '+JEV.res.calib+' · automatique','ok'); }
    EXPORT_AGENT.note('JEV','calibration automatique',{ok:true,steps:[H.length+' arrêtés en mémoire','données du jour APEX']}); }catch(e){ console.warn('JEV auto',e); } }
